//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRTaskBoardService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task_Tag = new HashSet<Task_Tag>();
            this.User_Task = new HashSet<User_Task>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorID { get; set; }
        public string Details { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Estimation { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> StageID { get; set; }
    
        public virtual Stage Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Tag> Task_Tag { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Task> User_Task { get; set; }
    }
}
